name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- master

variables:
  StatefileContext: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.Repository.Name)_$(Build.SourceBranchName)
  Subscription: AzureSP

stages:
- stage: CI
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Create storage artifact'
    pool: 
      name: 'private'
    steps:
    - publish: $(System.DefaultWorkingDirectory)/private_storage
      artifact: drop

- stage: dev  
  displayName: 'deploy dev'
  variables:
  - group: dev-variables

  jobs:
  - deployment: dev
    environment: dev
      pool: 
        name: 'private'
    strategy: 
      runOnce:
        preDeploy:
          steps:
          - download: current
            artifact: drop

        deploy:
          steps:
          - template: templates/terraform-steps.yml
            parameters:
              backendServiceArm: $(Subscription)
              workingDirectory: $(Pipeline.Workspace)/drop/tf
              backendAzureRmResourceGroupName: $(Tf.ResourceGroup)
              backendAzureRmStorageAccountName: $(Tf.StorageAccount)
              backendAzureRmContainerName: $(Tf.Container)
              environment: 'dev'
              statefileContext: $(StatefileContext)